# Generated by Django 4.2.4 on 2023-08-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('A', 'ace'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('T', '10'), ('J', '11'), ('Q', '12'), ('K', '13')], max_length=1)),
                ('suit', models.CharField(choices=[('H', 'Hearts'), ('C', 'Clubs'), ('S', 'Spades'), ('D', 'Diamonds')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='core.deck')),
            ],
        ),
    ]
